### PR TITLE
VIS-302: Add bootstrap into internal server

### PR DESCRIPTION
**Pull request by poliu2s**

### CODE REVIEW

**Comment by poliu2s** [comment]
Hey @kylezeeuwen, this ticket is for the addition of popovers for tooltips in rhtmlLabeledScatter (https://numbers.atlassian.net/browse/VIS-302) which require some CSS styling from bootstrap. Not sure if this is the best way to do it so open to hear your thoughts.

**Comment by kylezeeuwen** [comment]
Hi Po,

I would prefer not to add this to rhtmlBuildUtils. There is a way to define your own version of copy, and then do what you want (Alternative 1). There is also a way to modify gulp to add extra steps (Alternative 2). On the surface I prefer Alternative 2

*Alternative 1*

Have a look at https://github.com/Displayr/rhtmlDonut/blob/master/gulpfile.js, which does something similar.

So I think what you could do in the scatterplot gulpfile is to say dontRegisterTheseTasks = [ 'copy', 'other stuff']. Then just redefine gulp copy task in the scatter plot repo only, and make it copy whatever extras you need. 

*Alternative 2*

Stick with the default copy, and change the defintion of core. Have a look at https://github.com/Displayr/rhtmlBuildUtils/blob/master/src/index.js. You will see that copy is only called by core.

Currently "core" is defined as "['less', 'copy']", so in scatter you can say "dontRegisterTheseTasks = ['core', 'other stuff'], then defined core as ['less', 'copy', 'copy_bootstrap'], and define 'copy_bootstrap' to just copy the extra files you need.

**Comment by kylezeeuwen** [comment]
Let me know if those proposals work out for you, or if you need a hand

**Comment by poliu2s** [comment]
Thanks Kyle. I'll close this ticket and branch. Will work to implement the second option in rhtmlLabeledScatter.

**Pull request closed without merging**
